# Generated by Django 5.1.4 on 2025-01-03 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='is_delete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='expense',
            name='time_update',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
