# Generated by Django 5.1.4 on 2025-01-03 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0002_expense_is_delete_expense_time_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='category',
            name='is_archive',
            field=models.BooleanField(default=False),
        ),
    ]
