# Generated by Django 5.1.4 on 2025-01-15 22:00

import tracker_app.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0004_userexpenses'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='amount',
            field=models.DecimalField(decimal_places=2, max_digits=10, validators=[tracker_app.models.validate_positiv_decimal]),
        ),
    ]
