# Generated by Django 5.1.4 on 2025-01-15 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker_app', '0005_alter_expense_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='expense',
            name='desc',
            field=models.TextField(blank=True, null=True),
        ),
    ]
